markdown: rdiscount
#permalink: /:title.html
#base_url: http://jeffvincent.me
#description: "it's wonderful to have a beginner's mind"

auto: true
rdiscount extensions: [smart]
exclude:
- .gitignore
- README.md
