source "https://rubygems.org"
ruby "2.0.0"

gem "jekyll", "~> 1.0.0"
gem "sass"
gem "haml"
gem "compass"
gem "RedCloth"
gem "heroku", "~> 2.28.7"
gem 'rack-jekyll', :git => "https://github.com/adaoraul/rack-jekyll.git"
gem "unicorn", "~> 4.3.1"
gem "rdiscount", :git => "https://github.com/sunaku/rdiscount.git"
gem "foreman"
gem "gemoji"
